services:
  backend:
    build:
      context: ./GpsBackend
    ports:
      - "5141:80"

  frontend:
    build:
      context: ./gps-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend